apiVersion : apps/v1
kind: Deployment
metadata:
  name: ashwinsivadockerfiles 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashwinsivadockerfiles
  template:
    metadata:
      labels:
        app: ashwinsivadockerfiles 
    spec:
      containers:
        - name: ashwinsivadockerfiles 
          image: abx13.azurecr.io/ashwinsivadockerfiles
          ports:
          - containerPort: 9200
          readinessProbe:
            tcpsocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpsocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
