apiVersion : apps/v1
kind: Deployment
metadata:
  name: ashwinsivadockerfiles 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashwinsivadockerfiles
  template:
    metadata:
      labels:
        app: ashwinsivadockerfiles 
    spec:
      containers:
        - name: ashwinsivadockerfiles 
          image: abx13.azurecr.io/ashwinsivadockerfiles
          ports:
          - containerPort: 9200
          - protocol: "TCP"
            name: http
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 20
