apiVersion : apps/v1
kind: Deployment
metadata:
  name: ashwinsivadockerfiles 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashwinsivadockerfiles
  template:
    metadata:
      labels:
        app: ashwinsivadockerfiles 
    spec:
      containers:
        - name: ashwinsivadockerfiles 
          image: abx13.azurecr.io/ashwinsivadockerfiles
          ports:
          - containerPort: 9200
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 10
            periodSeconds: 24
