apiVersion : apps/v1
kind: Deployment
metadata:
  name: ashwinsivadockerfiles 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashwinsivadockerfiles
  template:
    metadata:
      labels:
        app: ashwinsivadockerfiles 
    spec:
      containers:
        - name: ashwinsivadockerfiles 
          image: abx13.azurecr.io/ashwinsivadockerfiles
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 20
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 25
            periodSeconds: 40
