apiVersion : apps/v1
kind: Deployment
metadata:
  name: ashwinsivadockerfiles 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashwinsivadockerfiles
  template:
    metadata:
      labels:
        app: ashwinsivadockerfiles 
    spec:
      containers:
        - name: ashwinsivadockerfiles 
          image: abx13.azurecr.io/ashwinsivadockerfiles
          ports:
          - containerPort: 9200
            name: http
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
